# Numpy Practice Questions

Topics:

1. Create Numpy arrays
2. Array Operations
3. Indexing and Slicing
4. Array Manipulation

# Create Numpy Arrays

## Problem 1:

Create a one dimensional array in Numpy.

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


## Problem 2:

Create a function to create a 2x2 matrix in Numpy.

In [2]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


## Problem 3:

Create an array filled with zeors.

In [4]:
c = np.zeros(4)
print(c)

[0. 0. 0. 0.]


## Problem 4:

Generate a array of random numbers.

In [6]:
d = np.random.random(5)
print(d)

[0.45248662 0.16687531 0.4811944  0.73119045 0.17694811]


## Problem 5:

Create an 1D array with int32 data type.

In [8]:
e = np.array([1,2,3,4,5], dtype=np.int32)
print(e.dtype)

int32


# Array Operations

## Problem 6:

Multiply each element of the array with 2.

In [10]:
a = np.array([1,2,3,4,5])
print(a*2)

[ 2  4  6  8 10]


## Problem 7:

Perform element-wise addition of two arrays.

In [11]:
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print(b1 + b2)

[[ 6  8]
 [10 12]]


## Problem 8:

Find the maximum value in an array.

In [12]:
a = np.array([4,7,2,6,9,1])
print(np.max(a))

9


## Problem 9:

Calculate the mean of an array.

In [13]:
print(np.mean(a))

4.833333333333333


## Problem 10:

Perform a dot product of two arrays.

In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

print(np.dot(a,b))

[[22 28]
 [49 64]]


# Indexing and Slicing

## Problem 11:

Access the third element in a 1D array.

In [15]:
a = np.array([1,2,3,4,5])
a[2]

3

## Problem 12:

Access the last row in a 2D array.

In [17]:
a = np.array([[1,2],[3,4]])
a[-1]

array([3, 4])

## Problem 13:

Access the odds columns with all rows in a 2D array.

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a[:,::2]

array([[1, 3],
       [4, 6]])

## Problem 14:

a =

    [[[11 21 31]
      [41 51 61]]

     [[71 81 91]
      [12 22 32]]]

Fetch elements 11, 31, 41 and 61 from the 3D array a.

In [19]:
a = np.array([[[11, 21, 31],[41, 51, 61]],  [[71, 81, 91],  [12, 22, 32]]])
print(a[0, :, ::2])

[[11 31]
 [41 61]]


## Problem 15:

From the above array print elements 12 and 22

In [20]:
print(a[1, 1, :2])

[12 22]


# Array Manipulation

## Problem 16:

Transpose a matrix in Numpy (2D array).

In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


## Problem 17:

Flatten a multi-dimensional array to 1D array.

In [25]:
print(np.ravel(a))

[1 2 3 4 5 6]


## Problem 18:

Join two 1D arrays horizontally.

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40])

np.hstack([a,b])

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40])

## Problem 19:

Join two 2D arrays vertically.

In [32]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[10,20], [30,40]])

np.vstack([a,b])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40]])

## Problem 20:

Split an array of shape (2,4) in two equall parts horizontally.

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
a1, a2 = np.hsplit(a,2)
print()
print(a1)
print()
print(a2)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [5 6]]

[[3 4]
 [7 8]]
